// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateFeed = { title: string, url: string, ttl: number, tag: string | null, tag_color: string | null, url_filter: Array<string> | null, };
