// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls how a feed's posts are displayed.
 * - `River`: posts show on the river (home view). Read/unread status is tracked.
 * - `FeedOnly`: posts don't show on the river. Only visible by navigating to the feed directly.
 *   Read/unread status is tracked.
 * - `Radar`: posts don't show on the river. Visible by navigating to the feed directly, and on the
 *   Radar section. Read/unread status is not tracked.
 */
export type DisplayMode = "river" | "feed_only" | "radar";
