// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebhookId } from "./WebhookId";
import type { WebhookKind } from "./WebhookKind";

export type FeedWebhookView = { attached: boolean, 
/**
 * Primary key
 */
id: WebhookId, 
/**
 * Label shown in the UI.
 */
name: string, 
/**
 * Endpoint the payload is POSTed to.
 */
url: string, 
/**
 * Selects the payload format.
 */
kind: WebhookKind, 
/**
 * JSON template rendered for `Custom` webhooks; ignored by the built-ins.
 */
payload_template?: string, created_at: string, };
