// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Feed = { id: number, title: string, url: string, ttl: number, url_filter: Array<string | null>, last_fetched_at?: string, created_at: string, tag?: string, tag_color?: string, };
