// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayMode } from "./DisplayMode";
import type { FeedId } from "./FeedId";
import type { FolderId } from "./FolderId";

export type Feed = { id: FeedId, 
/**
 * Human-readable feed name shown in the UI.
 */
title: string, 
/**
 * URL the feed is fetched from.
 */
url: string, 
/**
 * Refresh interval in minutes; the feed is polled once this much time has
 * elapsed since `last_fetched_at`.
 */
ttl: number, 
/**
 * Substrings that exclude a post when matched against its URL.
 */
filters: Array<string | null>, 
/**
 * Timestamp of the last successful poll; `None` until the feed is first fetched.
 */
last_fetched_at?: string, 
/**
 * Timestamp the feed was added.
 */
created_at: string, 
/**
 * Optional folder used to group and filter feeds.
 */
folder_id?: FolderId, 
/**
 * Whether the feed is paused (not polled by the worker).
 */
is_paused: boolean, 
/**
 * Dictates how posts from a feed are displayed.
 * See the enum above.
 */
display_mode: DisplayMode, };
