// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A join-table row linking a feed to a webhook (many-to-many): a feed can have
 * many webhooks and a webhook can serve many feeds. Rows are managed via
 * [`FeedWebhook::create`]/[`FeedWebhook::delete`] and cascade-deleted when
 * either the feed or the webhook is removed.
 */
export type FeedWebhook = { feed_id: number, webhook_id: number, };
