// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationCursor } from "./PaginationCursor";

export type ListPosts = { page: PaginationCursor | null, tag: string | null, search: string | null, };
