// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedId } from "./FeedId";
import type { PaginationCursor } from "./PaginationCursor";

export type ListPosts = { page?: PaginationCursor, feed_id?: FeedId, bookmarked?: boolean, unread_only?: boolean, search?: string, exclude?: Array<FeedId>, };
