// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedId } from "./FeedId";
import type { FolderId } from "./FolderId";

export type MarkRead = { feed_id: FeedId | null, folder_id: FolderId | null, };
