// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Post } from "./Post";

export type PostsPage = { items: Array<Post>, has_more: boolean, };
