// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry fetched from a feed.
 */
export type Post = { 
/**
 * Primary key.
 */
id: number, 
/**
 * The feed this post belongs to; the row is removed when that feed is
 * deleted (`ON DELETE CASCADE`).
 */
feed_id: number, 
/**
 * Post title, or `None` if the feed entry has none.
 */
title?: string, 
/**
 * Link to the original post. Forms the `(feed_id, url)` uniqueness
 * constraint used to dedupe on re-fetch.
 */
url?: string, 
/**
 * Comma-separated author list, each formatted as `name (email)` (or just
 * `name`); `None` if the entry lists no authors.
 */
authors?: string, 
/**
 * When the entry was published; defaults to insertion time if the feed
 * omits it.
 */
published_at: string, 
/**
 * When the entry was last updated, if the feed provides it.
 */
updated_at?: string, 
/**
 * Short summary or excerpt (the feed's summary, falling back to a media
 * description for media feeds).
 */
description?: string, 
/**
 * Full post body, if the feed includes it.
 */
content?: string, 
/**
 * Whether the user has favorited this post.
 */
is_favorite: boolean, 
/**
 * Whether the post has been marked read.
 */
is_read: boolean, 
/**
 * Whether the post has been archived.
 */
is_archived: boolean, };
