// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A snapshot of an archived post, kept independently of the `posts` table so
 * it survives the original post (and its feed) being deleted.
 */
export type PostArchive = { 
/**
 * The original post's id, reused as this row's primary key — there is no
 * foreign key back to `posts`, so the archive outlives the post.
 */
id: number, 
/**
 * Post title at the time it was archived.
 */
title?: string, 
/**
 * Link to the original post.
 */
url?: string, 
/**
 * Comma-separated author list captured from the post.
 */
authors?: string, 
/**
 * The post's original publish timestamp.
 */
published_at: string, 
/**
 * Short summary or excerpt captured from the post.
 */
description?: string, 
/**
 * Full post body captured from the post.
 */
content?: string, 
/**
 * Tag copied from the owning feed when archived, so it persists even after
 * the feed is gone.
 */
tag?: string, 
/**
 * Hex color for `tag`, likewise copied from the feed.
 */
tag_color?: string, 
/**
 * When the post was archived.
 */
archived_at: string, };
