// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Post = { id: number, feed_id: number, title?: string, url?: string, authors?: string, published_at: string, updated_at?: string, description?: string, content?: string, is_favorite: boolean, is_read: boolean, };
