// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostArchive = { id: number, title?: string, url?: string, authors?: string, published_at: string, description?: string, content?: string, tag?: string, tag_color?: string, archived_at: string, };
