// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Post = { id: number, feed_id: number, title: string | null, url: string | null, authors: string | null, published_at: string, updated_at: string | null, description: string | null, content: string | null, is_favorite: boolean, is_read: boolean, };
