// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls when posts are marked as read.
 * - `OnOpen`: automatically marked read when opened in the reader.
 * - `Manually`: only marked read via the toggle button.
 * - `Disabled`: read state is never updated; all posts appear as read.
 */
export type ReadMode = "on_open" | "manually" | "disabled";
