// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadMode } from "./ReadMode";

export type Settings = { 
/**
 * Number of posts returned per page when listing.
 */
page_size: number, 
/**
 * How often feeds are polled for new posts, in seconds.
 */
feed_poll_interval_secs: number, 
/**
 * Total timeout for a feed HTTP request, in seconds.
 */
http_timeout: number, 
/**
 * Timeout for establishing the connection to a feed host, in seconds.
 */
http_connect_timeout: number, 
/**
 * Number of times a failed feed request is retried.
 */
http_retries: number, 
/**
 * Custom `User-Agent` header sent when fetching feeds; `None` uses the
 * default.
 */
http_user_agent?: string, 
/**
 * When posts get marked as read (see [`ReadMode`]).
 */
read_mode: ReadMode, };
