// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadMode } from "./ReadMode";

export type Settings = { page_size: number, feed_poll_interval_secs: number, http_timeout: number, http_connect_timeout: number, http_retries: number, http_user_agent?: string, read_mode: ReadMode, };
