// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateSettings = { page_size: number | null, feed_poll_interval_secs: number | null, http_timeout: number | null, http_connect_timeout: number | null, http_retries: number | null, http_user_agent: string | null, };
