// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebhookKind } from "./WebhookKind";

export type UpdateWebhook = { name?: string, url?: string, kind: WebhookKind, payload_template?: string, };
