// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateFeed = { title: string | null, url: string | null, ttl: number | null, url_filter: Array<string> | null, };
