// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateFeed = { title: string | null, url: string | null, ttl: number | null, 
/**
 * Absent (None) = keep the current folder;
 * `null` or blank (Some(None)) = remove the feed from its folder;
 * a name (Some(Some("name"))) = assign (creating the folder if needed).
 */
folder?: string | null, filters: Array<string> | null, };
