// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebhookKind } from "./WebhookKind";

/**
 * A reusable notification destination. A webhook is created independently and
 * attached to any number of feeds via the `feed_webhooks` join table; when a
 * feed gets new posts, the worker POSTs the rendered [`WebhookKind`] payload
 * to its `url`.
 */
export type Webhook = { 
/**
 * Primary key
 */
id: number, 
/**
 * Label shown in the UI.
 */
name: string, 
/**
 * Endpoint the payload is POSTed to.
 */
url: string, 
/**
 * Selects the payload format.
 */
kind: WebhookKind, 
/**
 * JSON template rendered for `Custom` webhooks; ignored by the built-ins.
 */
payload_template?: string, created_at: string, };
