[package]
name = "wyrm-rss"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
reqwest-retry = { workspace = true }
reqwest-middleware = { workspace = true }
feed-rs = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
quick-xml = { workspace = true }
scraper = { workspace = true }
wyrm_utils = { path = "../utils" }
wyrm_webhook = { path = "../webhook", default-features = false }
database = { path = "../database", default-features = false }
async-trait = "0.1.89"
http = "1.4.1"
bytes = "1.11.1"

[features]
default = ["postgres"]
postgres = ["database/postgres", "wyrm_webhook/postgres"]
sqlite = ["database/sqlite", "wyrm_webhook/sqlite"]
