[package]
name = "server"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
actix-web = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
api_routes = { path = "../api/routes" }
api_utils = { path = "../api/utils" }
database = { path = "../database" }
utils = { path = "../utils" }
wyrm-rss = { path = "../rss" }
