[package]
name = "database"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ts-rs = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
diesel_migrations = { workspace = true }
diesel-derive-enum = { workspace = true }
chrono = { workspace = true }
feed-rs = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
wyrm_utils = { path = "../utils" }

[dev-dependencies]
tokio = { workspace = true }
