// `macro_use` re-exports the test fixture macros (`test_feed!`/`test_post!`)
// declared inside `models` so the `views` tests can use them too.
#[macro_use]
pub mod models;
pub mod newtypes;
// Both files are generated by `diesel print-schema` (see diesel.toml); the
// `#[path]` keeps `crate::schema::*` resolving the same under either backend.
#[cfg(feature = "postgres")]
pub mod schema;
#[cfg(feature = "sqlite")]
#[path = "schema_sqlite.rs"]
pub mod schema;
pub mod utils;
pub mod views;
use diesel::Connection;
use diesel_async::pooled_connection::{AsyncDieselConnectionManager, deadpool::Pool};
use diesel_migrations::{EmbeddedMigrations, MigrationHarness, embed_migrations};
use std::error::Error;
use wyrm_utils::{
    config::WyrmStartupConfig,
    error::{DatabaseError, WyrmError},
    result::WyrmResult,
};

// Exactly one backend, since the aliases below name a single connection type.
// See the note in Cargo.toml about why a sqlite consumer can't share the root
// workspace.
#[cfg(all(feature = "postgres", feature = "sqlite"))]
compile_error!(
    "features `postgres` and `sqlite` are mutually exclusive — a sqlite consumer must set \
     `default-features = false` and live outside the root workspace"
);
#[cfg(not(any(feature = "postgres", feature = "sqlite")))]
compile_error!("enable exactly one of the `postgres` or `sqlite` features");

/// Case-insensitive `LIKE` against a text column.
///
/// Postgres needs `ILIKE`; SQLite's `LIKE` is already case-insensitive for
/// ASCII, and has no `ILIKE` at all. Neither folds case beyond ASCII, so the two
/// agree in practice for the search this backs.
// cfg the definition rather than the body: a `#[cfg]`'d block inside the
// expansion sits in statement position and evaluates to `()`.
#[cfg(feature = "postgres")]
#[macro_export]
macro_rules! ci_like {
    ($column:expr, $pattern:expr) => {
        diesel::PgTextExpressionMethods::ilike($column, $pattern)
    };
}

#[cfg(feature = "sqlite")]
#[macro_export]
macro_rules! ci_like {
    ($column:expr, $pattern:expr) => {
        diesel::TextExpressionMethods::like($column, $pattern)
    };
}

/// The diesel backend in use. Referenced by every model's
/// `#[diesel(check_for_backend(...))]` so the derives follow the active feature
/// instead of hardcoding `diesel::pg::Pg`.
#[cfg(feature = "postgres")]
pub type Backend = diesel::pg::Pg;
#[cfg(feature = "sqlite")]
pub type Backend = diesel::sqlite::Sqlite;

/// Blocking connection, used only to apply migrations at startup.
#[cfg(feature = "postgres")]
pub type SyncConnection = diesel::PgConnection;
#[cfg(feature = "sqlite")]
pub type SyncConnection = diesel::SqliteConnection;

/// SQLite has no native async driver, so it goes through diesel-async's
/// `SyncConnectionWrapper`, which runs the blocking calls on
/// `spawn_blocking`. Call sites stay `async` either way.
#[cfg(feature = "postgres")]
pub type DatabaseConn = diesel_async::AsyncPgConnection;
#[cfg(feature = "sqlite")]
pub type DatabaseConn =
    diesel_async::sync_connection_wrapper::SyncConnectionWrapper<diesel::SqliteConnection>;

pub type DatabasePool = Pool<DatabaseConn>;

#[cfg(feature = "postgres")]
pub const MIGRATIONS: EmbeddedMigrations = embed_migrations!("../migrations/");
#[cfg(feature = "sqlite")]
pub const MIGRATIONS: EmbeddedMigrations = embed_migrations!("../migrations_sqlite/");

pub fn run_migrations(
    connection: &mut SyncConnection,
) -> Result<(), Box<dyn Error + Send + Sync + 'static>> {
    connection.run_pending_migrations(MIGRATIONS)?;
    Ok(())
}

/// For sqlite, `database_connection` is a file path rather than a URL.
pub fn establish_sync_connection(conf: &WyrmStartupConfig) -> WyrmResult<SyncConnection> {
    let conn = SyncConnection::establish(&conf.database_connection)?;
    Ok(conn)
}

#[cfg(feature = "postgres")]
fn connection_manager(conf: &WyrmStartupConfig) -> AsyncDieselConnectionManager<DatabaseConn> {
    AsyncDieselConnectionManager::new(&conf.database_connection)
}

/// SQLite applies pragmas per connection, so each one the pool opens needs
/// them: without `foreign_keys` every `ON DELETE` clause in the schema is
/// silently inert, and without WAL plus a busy timeout any pool wider than one
/// returns `SQLITE_BUSY` the moment two writes overlap.
#[cfg(feature = "sqlite")]
fn connection_manager(conf: &WyrmStartupConfig) -> AsyncDieselConnectionManager<DatabaseConn> {
    use diesel_async::{AsyncConnection, SimpleAsyncConnection, pooled_connection::ManagerConfig};

    let mut config = ManagerConfig::default();
    config.custom_setup = Box::new(|url| {
        Box::pin(async move {
            let mut conn = DatabaseConn::establish(url).await?;
            conn.batch_execute(
                "PRAGMA foreign_keys = ON; \
                 PRAGMA journal_mode = WAL; \
                 PRAGMA busy_timeout = 5000; \
                 PRAGMA synchronous = NORMAL;",
            )
            .await
            .map_err(diesel::ConnectionError::CouldntSetupConfiguration)?;
            Ok(conn)
        })
    });

    AsyncDieselConnectionManager::new_with_config(&conf.database_connection, config)
}

pub async fn create_pool(conf: &WyrmStartupConfig) -> WyrmResult<DatabasePool> {
    Pool::builder(connection_manager(conf))
        .max_size(conf.database_pool_size)
        .build()
        .map_err(|e| WyrmError::Database(DatabaseError::PoolBuildError(e)))
}

/// Builds a connection pool against the configured test database, ensuring the
/// schema is migrated first.
///
/// Migrations are applied at most once per test process (via [`Once`]), so it's
/// cheap for every database test to call this — the first call sets up the
/// schema, later calls just hand back a fresh pool. Applying the embedded
/// migrations mirrors what the server does on startup, so a blank database
/// (e.g. CI's Postgres service) gets set up the same way `diesel migration run`
/// would, without needing the diesel CLI installed.
/// Postgres only: `WyrmStartupConfig` points at a server, and the tests that
/// use this expect CI's service container. The sqlite backend is covered by
/// `tests/sqlite_smoke.rs`, which builds its own temp-file database instead.
#[cfg(all(test, feature = "postgres"))]
pub(crate) async fn setup_test_db() -> DatabasePool {
    static INIT: std::sync::Once = std::sync::Once::new();

    INIT.call_once(|| {
        // `load()` resolves config/wyrm.toml relative to the cwd, but tests run
        // from the crate dir — point at the workspace root so we read the same
        // config the server uses. Done once, before any `load()` below.
        std::env::set_current_dir(concat!(env!("CARGO_MANIFEST_DIR"), "/.."))
            .expect("should cd to workspace root");

        let conf = WyrmStartupConfig::load().expect("should load test config");
        let mut conn = establish_sync_connection(&conf).expect("should connect for migrations");
        run_migrations(&mut conn).expect("should run migrations");
    });

    let conf = WyrmStartupConfig::load().expect("should load test config");
    create_pool(&conf)
        .await
        .expect("should build pool against the test database")
}
