[package]
name = "api_api"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
actix-web = { workspace = true }
api_utils = { path = "../utils" }
wyrm_utils = { path = "../../utils" }
database = { path = "../../database" }
wyrm-rss = { path = "../../rss" }
