[package]
name = "api_api"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
api_utils = { path = "../utils" }
utils = { path = "../../utils" }
database = { path = "../../database" }
