[package]
name = "api_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
api_utils = { path = "../utils" }
utils = { path = "../../utils" }
database = { path = "../../database" }
