[package]
name = "api_utils"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
actix-web = { workspace = true }
serde = { workspace = true }
database = { path = "../../database" }
wyrm-rss = { path = "../../rss" }
