[package]
name = "api_utils"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
utils = { path = "../../utils" }
database = { path = "../../database" }
wyrm-rss = { path = "../../rss" }
