[package]
name = "api_utils"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
actix-web = { workspace = true }
serde = { workspace = true }
database = { path = "../../database", default-features = false }
wyrm-rss = { path = "../../rss", default-features = false }

[features]
default = ["postgres"]
postgres = ["database/postgres", "wyrm-rss/postgres"]
sqlite = ["database/sqlite", "wyrm-rss/sqlite"]
