[package]
name = "api_routes"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
actix-web = { workspace = true }
api_api = { path = "../api" }
api_crud = { path = "../crud" }
